# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_mainshow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainshow',
            old_name='children1',
            new_name='childcid1',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='children2',
            new_name='childcid2',
        ),
        migrations.RenameField(
            model_name='mainshow',
            old_name='children3',
            new_name='childcid3',
        ),
    ]
