# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 07:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_foodtype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Foodtype',
            new_name='Foodtypes',
        ),
        migrations.AlterModelTable(
            name='foodtypes',
            table='axf_foodtypes',
        ),
    ]
